(function(f,h,m,l,d){f[h]=f[h]||{};for(f[h].q=f[h].q||[];d<l.length;)m(l[d++],f[h])})(window,"extole",function(f,h){h[f]=h[f]||function(){h.q.push([f,arguments])}},["log"],0);
extole.define||function(){function f(a){a=d(a);return y[a]}function h(a,b){extole.log("error","[REQUIRE] "+a,b)}function m(a,b){if(a.length)for(var p=0;p<a.length;p++)b(a[p],p);else for(p in a)Object.prototype.hasOwnProperty.call(a,p)&&b(a[p],p)}function l(a,b){var p=[];m(a,function(a,e){p[e]=b(a,e)});return p}function d(a){return"string"!==typeof a?a:/origin-\d/.test(a)?a.substring(a.indexOf("type=")).replace(/version=\d+:/,""):a}function n(a){var b=a.split("/").slice(-1)[0],p=b.length;m(b.toLowerCase(),
function(a){p+=" abcdefghijklmnopqrstuvwxyz1234567890-_.".indexOf(a)});return a.replace("origin","origin-"+p%8)}function k(a){var b=/^extole-creatives:/.test(a),e=/^extole-media:/.test(a),g=/^core-root:\/\//.test(a),c=/^extole-assets:/.test(a),p=/origin\./.test(a),r=/^http:/.test(a),d=/^https:/.test(a);return b?(a=a.slice(17),k("extole-assets:/core-modules/"+a)):c?(a=a.slice(14),k("extole-media:/assets/"+a)):e?(a=a.slice(13),a=extole.CORE_ROOT+a,k(a)):g?(a=a.slice(12),a=extole.CORE_ROOT+a,k(a)):p?
(a=n(a),a+="?site="+window.location.hostname,k(a)):r?(a=a.slice(5),k(a)):d?(a=a.slice(6),k(a)):a}function c(){}function b(){var a="undefined"!==typeof window.opera&&"[object Opera]"===window.opera.toString(),b=document.createElement("script");this.useInteractive=b.attachEvent&&!(b.attachEvent.toString&&0>b.attachEvent.toString().indexOf("[native code"))&&!a}function a(){m(y,function(a){a._fetched?a._defined||a.define():a.fetch()})}function g(a,b,e,g,r){if("$config"!=a){var p=f(a),q=p||new c;p||(p=
d(a),y[p]=q);a&&b&&(q._fetched=!0);q.start=q.start||(new Date).getTime();q.url=q.url||a;q.dependencies=q.dependencies||b;q.config=q.config||g;q.definedCallback=q.definedCallback||e;q.isRequire=q.isRequire||r}}function e(a,b,e,g){a instanceof Array&&(g=e,e=b,b=a,a=void 0);w.addDefine({url:a,dependencies:b,definedCallback:e,config:g})}function r(){u++;return"anonymous_"+u}var y={};c.prototype={getUnresolvedDependencies:function(){var a=[];m(this.dependencies,function(b){"$config"!=b&&(b=f(b),(!b||b&&
!b._defined)&&a.push(b))});return a},getDependencies:function(){var a=this,b=[];m(a.dependencies,function(e){e="$config"==e?a.config||null:f(e).definition||null;b.push(e)});return b},define:function(){function b(b){e.definedCallback=void 0;e.definition=b;e.end=(new Date).getTime();e.timeToDefine=e.end-e.start;e._defining=!1;e._defined=!0;setTimeout(a,1)}var e=this;e.defineStartTime=e.defineStartTime||(new Date).getTime();if(!e._defining&&!e._defined&&e.dependencies)if(e._defining=!0,0<e.getUnresolvedDependencies().length)e._defining=
!1;else{var g=e.getDependencies(),c={isAsync:!1,async:function(){e.isAsync=!0;c.isAsync=e.isAsync;return function(a){b(a)}}};(function(){if(e.definedCallback){var a=e.definedCallback;a=a&&a.apply(c,g);c.isAsync||b(a)}else b(!0)})()}},fetch:function(){var a=this;a._fetching||a._fetched||(a.url?(a._fetching=!0,a.startFetchTime=(new Date).getTime(),w.loadModule(a.url,function(){a._fetching=!1;a.endFetchTime=(new Date).getTime();a.timeToFetch=a.endFetchTime-a.startFetchTime;a._fetched=!0;a.define()})):
h("Tried to fetch a module without a url - dependencies: "+a.dependencies+" definedCallback: "+(a.definedCallback?"exists":"null")+" config: "+a.config))}};b.prototype={defineQueue:[],interactiveScript:null,currentlyAddingScript:null,getInteractiveScript:function(){if(w.interactiveScript&&"interactive"==w.interactiveScript.readyState)return w.interactiveScript;for(var a=document.getElementsByTagName("head")[0].getElementsByTagName("script"),b,e=a.length-1;0<=e;e--){var g=this.getScriptDataUrl(a[e]);
a[e]&&"interactive"==a[e].readyState&&g&&(b=a[e])}return b},scriptUrlAttributeName:"data-extole-require-url",getScriptDataUrl:function(a){return a.getAttribute(this.scriptUrlAttributeName)},setScriptDataUrl:function(a,b){a.setAttribute(this.scriptUrlAttributeName,b)},attachOnLoad:function(a,b){function e(r){var d=a.readyState;if(g&&"interactive"==d)this.interactiveScript=a;else if("load"===r.type||c.test(d))g?a.detachEvent("onreadystatechange",e):a.removeEventListener("load",e,!1),b(r)}b=b||function(){};
var g=this.useInteractive,c="PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/;g?a.attachEvent("onreadystatechange",e):a.addEventListener("load",e,!1)},defineTimeout:null,addDefine:function(a){if(a.url)a.url=k(a.url);else{var b=this.currentlyAddingScript||this.getInteractiveScript();this.useInteractive&&b&&(b=this.getScriptDataUrl(b),a.url=b,this.interactiveScript=null)}a.dependencies=l(a.dependencies,k);this.useInteractive&&!a.url&&h("defines should not be missing a url in ie.");
this.defineQueue.push(a);this.defineTimeout&&clearTimeout(this.defineTimeout);var e=this;this.defineTimeout=setTimeout(function(){e.intakeDefines()},1)},intakeTimeout:null,intakeDefines:function(){for(var b=[],e;e=this.defineQueue.shift();){var c=[];m(e.dependencies,function(a){a&&c.push(a)});e.url&&f(e.url);e.url||b.push("deps "+e.dependencies);m(c,function(a){g(a)});g(e.url,c,e.definedCallback,e.config,e.isRequire)}this.intakeTimeout&&clearTimeout(this.intakeTimeout);this.intakeTimeout=setTimeout(a,
1)},loadModule:function(a,b){var e=document.createElement("script");e.async=!0;e.crossOrigin="anonymous";this.setScriptDataUrl(e,a);var g=this;this.attachOnLoad(e,function(){clearTimeout(c);if(!g.useInteractive){for(var e,r=g.defineQueue.length-1;0<=r;r--)g.defineQueue[r].url||(e&&h("Multiple anonymous modules loaded in one script - "+a),e=g.defineQueue[r]);e&&(e.url=a)}g.intakeDefines();b&&b(null)});e.src=a;var c=setTimeout(function(){extole.log("warn","[REQUIRE] Module did not load within 2000ms: ",
{moduleUrl:a})},2E3);this.currentlyAddingScript=e;var r=document.getElementsByTagName("head")[0]||document.head;r?r.appendChild(e):extole.log("warn","[REQUIRE] <head> element not found on trying to load "+a,void 0);this.currentlyAddingScript=void 0}};var w=new b;e.getModule=function(a){return f(a)};var u=0;extole.define=e;extole.require=function(a,b){w.addDefine({url:r(),dependencies:a,definedCallback:b,isRequire:!0})};extole.define("extole-require",[],function(){return{resolveUrl:k}});setTimeout(function(){var a=
!1,b=[];m(y,function(e){e._defined||(a=!0);b.push({defineStartTime:e.defineStartTime,dependencies:e.dependencies,end:e.end,start:e.start,isRequire:e.isRequire,timeToDefine:e.timeToDefine,url:e.url,_defined:e._defined,_defining:e._defining,_fetched:e._fetched})});a&&extole.DUMP_REQUIRE_MODULES_ON_ERROR&&extole.log("error","After 7000ms there are unresolved extole-require modules.  ###"+JSON.stringify(b)+"###")},7E3)}();
(function(){try{(function(f,h,m,l,d){f[h]=f[h]||{};for(f[h].q=f[h].q||[];d<l.length;)m(l[d++],f[h])})(window,"extole",function(f,h){h[f]=h[f]||function(){h.q.push([f,arguments])}},["createZone"],0),(new Function('extole.isFindElementBeforeZoneRequest = true;\n\nextole.createZonePrehandler = function (zoneDefinition, zoneData) {\n    "use strict";\n    if (zoneDefinition.name === "global_header") {\n        if (!zoneData.partner_user_id) {\n            return false;\n        }\n\n        var stringifiedParams = JSON.stringify([zoneDefinition, zoneData]);\n        \n        if (extole.globalHeaderParams === stringifiedParams) {\n            return false;\n        }\n\n        extole.globalHeaderParams = stringifiedParams;\n        return true;\n    }\n};'))()}catch(f){extole.log("error",
"Error executing extended core javascript. Message: "+f.message+" Stack: "+f.stack)}})();
extole.define("extole-uri-parser",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/collection.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/uri.js"],function(f,h){var m=/^extole_(?!zone)/,l=/^extole_zone_/;return new function(){function d(c){var b={};c=c||k;f.each(c,function(a,g){m.test(g)&&(g=g.replace(m,""),b[g]=a)});return b}function n(){var c,b,a={};this.withName=function(a){c=a;return this};this.withElementId=function(a){b=
a;return this};this.withData=function(b,e){a[b]=e;return this};this.build=function(){var g={};c&&(g.name=c);b&&(g.elementId=b);a&&(g.data=a);return g}}var k=h.deserialize(location.search);this.parseUriZoneDefinition=function(c){var b=new n,a;c=c||k;var g=d(c);f.each(g,function(a,g){b.withData(g,a)});f.each(c,function(e,g){l.test(g)&&(g=g.replace(l,""),"name"===g?(a=!0,b.withName(e)):"element_id"===g?b.withElementId(e):b.withData(g,e))});return a?b.build():null};this.parseGlobalZoneParameters=d}});
(function(f,h,m,l,d){f[h]=f[h]||{};for(f[h].q=f[h].q||[];d<l.length;)m(l[d++],f[h])})(window,"extole",function(f,h){h[f]=h[f]||function(){h.q.push([f,arguments])}},["createZone","log"],0);
(function(){var f=[{name:"Shutterstock Branded Domain",programDomain:"share.shutterstock.com",sitePatterns:["share.shutterstock.com","shutterstock.com","*.shutterstock.com","shuttercloud.org","*.shuttercloud.org"],siteRegexPatterns:["share\\.shutterstock\\.com\\.?$","shutterstock\\.com\\.?$",".*\\.shutterstock\\.com\\.?$","shuttercloud\\.org\\.?$",".*\\.shuttercloud\\.org\\.?$"]}];extole.CORE_ROOT="https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144";extole.CORE_CONFIG={backendTargetingEnabled:!0,
isZonePostEnabled:!0,isCookieConsentEnabled:!1,isJsCreativeRespondsWithHtmlEnabled:!1,isGlobalZoneParametersEnabled:!1,isAccessTokenIncludedInResponseEnabled:!0,cookieConsentPolicy:"COOKIE_CONSENT_OR_SESSION_COOKIE",zonePostEnabled:!0,cookieConsentEnabled:!1};extole.CLIENT_ID="1528233037";extole.BUILD_DATE="1679937874903";extole.VERSION="6.0";extole.IS_DEBUG_ENABLED=extole.debug||/[?&]extole_debug=true(&|$)/.test(location.search);extole.PROGRAM=function(){function h(b,a){b=Error.call(this,b);this.name=
"ExtoleError";this.message=b.message;this.stack=b.stack;this.code=a}function m(b,a){if(b.length)for(var g=0;g<b.length;g++)a(b[g],g);else for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&a(b[g],g)}function l(b,a){var g=[];m(b,function(b){(b=a(b))&&(g[g.length]=b)});return g}function d(b,a){a=a||[];var g=!1;m(a,function(a){(new RegExp(a)).test(b)&&(g=!0)});return g}function n(){extole.require(["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/uri.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/ajax.js"],
function(b,a){var g=extole.CORE_ROOT;b=g.replace(/(https?:\/\/[a-z-\.]+)(\/.*)/,"$1")+"/_extole_core.gif"+b.serialize({core_root:g,referer:window.location.hostname});a({url:b})})}h.prototype=Error();h.prototype.constructor=h;var k=function(b){var a=window.location.hostname;return l(b,function(b){if(d(a,b.siteRegexPatterns))return b})}(f),c=k[0];if(!c)throw n(),new h("No program domain is configured for hostname: "+window.location.hostname+" unable to use Extole API","site_configuration_error");1<
k.length&&extole.log("warn","Multiple programs matched hostname: "+window.location.hostname+" programs: "+JSON.stringify(k));return c}();extole.require(["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/uri.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js","create-zone-executor"],function(h,f,l){function d(){function b(b){var e=b[0];"function"===typeof a[e]?(a[e].apply(null,b[1]),extole.q.history.push({name:b[0],args:b[1],
timestamp:Date.now(),stack:Error().stack})):f.warn("Unable to execute method: "+e+", it is not implemented.")}var a={log:function(){var a=Array.prototype.slice.call(arguments),b=a[0];"function"===typeof f[b]&&f[b].apply(null,a.slice(1))},createZone:l.initiateExecution};for(extole.q.history=[];extole.q.length;)b(extole.q.shift());extole.q.push=b}function n(){extole.require(["extole-uri-parser"],function(b){var a=h.deserialize(location.search);(b=b.parseUriZoneDefinition(a))&&extole.createZone(b)})}
function k(){if("function"===typeof window.onerror)var b=window.onerror;window.onerror=function(a,g,e,c,d){if(b)try{b(a,g,e,c,d)}catch(p){}g=g||window.location.href||"no_source_or_location.href";d=d&&d.stack?d.stack:"no_error.stack";var r=[],k=JSON.stringify({MESSAGE:a,SOURCE:g,LINE_NUMBER:e,COLUMN_NUMBER:c,STACK_TRACE:d},function(a,b){if(null!==b&&"object"===typeof b){if(0<=r.indexOf(b))return;r.push(b)}return b});e=extole.PROGRAM.programDomain.split(".").join("\\.");e=new RegExp("^(http|https):\\/\\/("+
e+"|(([A-Za-z0-9-]{1,}\\.){1,}|)(xtlo\\.net|extole(\\.com|\\.io)))(?=(\\/|\\?|$))");((d+a).match(/extole/i)||e.test(g))&&extole.require(["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js"],function(a){a.error("Unhandled exception",JSON.parse(k))})}}function c(){extole._bootstrapped=!0;k();d();n()}extole.bootstrap=c;extole._bootstrapped||c();if("undefined"!==typeof window.extoleAsyncInit)try{window.extoleAsyncInit()}catch(b){extole.require(["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js"],
function(a){a.error("Error executing extended core javascript. Message : "+b.message+" Stack: "+b.stack)})}})})();
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/ExtoleError.js",[],function(){function f(f,l,d,n){f=Error.call(this,f);this.name="ExtoleError";this.message=f.message||"no_message";this.stack=Error().stack;this.code=l||"extole_error";this.data=d||{};this.logLevel=0<=h.indexOf(n)?n:"error"}var h=["debug","info","warn","error"];f.prototype=Error();f.prototype.constructor=f;f.prototype.toString=function(){return this.name+" ["+this.logLevel+"]: message: "+
this.message+"; code: "+this.code+"; data: "+JSON.stringify(this.data,null,4)+"; stack trace: "+this.stack+";"};return f});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/collection.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/ExtoleError.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/type.js"],function(f,h){function m(d,f){var k;if(d.length===Number(d.length))for(k=0;k<d.length;k++){var c=f(d[k],k);if(!1===c)return!1}else for(k in d)if(Object.prototype.hasOwnProperty.call(d,k)&&(c=f(d[k],
k),!1===c))return!1}function l(d){if(!d||"object"!==typeof d&&!h.isPlainFunction(d))d={};for(var f=1;f<arguments.length;f++)if(h.isPlainObject(arguments[f]))for(var k in arguments[f]){var c=arguments[f][k];c!==d&&void 0!==c&&(h.isPlainObject(c)&&h.isPlainObject(d[k])?c=l(d[k],c):h.isArray(c)&&h.isArray(d[k])&&d[k].concat&&(c=d[k].concat(c)),d[k]=c)}return d}m.BREAK=!1;return{each:m,map:function(d,l){function k(a,c){b=[];m(a,function(a,g){b.push(c(a,g))})}function c(a,c){b={};m(a,function(a,g){b[g]=
c(a,g)})}var b;if(h.isArray(d))k(d,l);else if(h.isPlainObject(d))c(d,l);else throw new f(d+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return b},filter:function(d,l){function k(a,c){b=[];m(a,function(a,g){c(a,g)&&b.push(a)})}function c(a,c){b={};m(a,function(a,g){c(a,g)&&(b[g]=a)})}var b;if(h.isArray(d))k(d,l);else if(h.isPlainObject(d))c(d,l);else throw new f(d+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return b},merge:l,clone:function(d){return JSON.parse(JSON.stringify(d))},
flatten:function(d){function f(c,b){if(h.isPlainObject(c))m(c,function(a,e){var c=b.slice();c.push(e);f(a,c)});else{var a=b.join(".");k[a]=c}}if(!h.isPlainObject(d))return d;var k={};f(d,[]);return k},find:function(d,f){var k;m(d,function(c,b){if(f(c,b))return k=c,m.BREAK});return k},reverse:function(d){var f=[];if(!d||d.length!==Number(d.length))return d;for(var k=d.length-1;0<=k;k--)f.push(d[k]);return f},nashornToJs:function(d){if(h.isPlainJs(d)||!d)return d;if(h.isJavaMap(d)){var f={};for(var k in d)f[k]=
d[k]}else if(h.isNumber(d.length))f=[],m(d,function(c,b){f[b]=c});else return d;return f},intersection:function(d,f){var k=[];m(d,function(c){0>f.indexOf(c)||0<=k.indexOf(c)||k.push(c)});return k},difference:function(d,f){var k=[];m(d,function(c){0<=f.indexOf(c)||0<=k.indexOf(c)||k.push(c)});return k}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/cookie.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js"],function(f){function h(c){try{return decodeURIComponent(c.replace(d," "))}catch(b){return f.info("** cookie.decode ** Cookie error for: "+c,{error:b,message:b.message,stack:b.stack,cookiePart:c}),""}}function m(c){c=h(c);return 0===c.indexOf('"')?c.slice(1,-1).replace(n,'"').replace(k,"\\"):c}function l(c){if(!c||
!c.toUTCString){var b=new Date;b.setDate(b.getDate()+("number"===typeof c?c:0));return b}return c}var d=/\+/g,n=/\\"/g,k=/\\\\/g;return function(c,b,a){if(void 0!==b)return a=a||{},document.cookie=[encodeURIComponent(c),"=",encodeURIComponent(b),a.expires?"; expires="+l(a.expires).toUTCString():"",a.path?"; path="+a.path:"",a.domain?"; domain="+a.domain:"",a.samesite?"; samesite="+a.samesite:"","; secure"].join("");a:{b=document.cookie?document.cookie.split("; "):[];a=c?null:{};for(var g=0,e=b.length;g<
e;g++){var d=b[g].split("="),k=h(d[0]);if(!c)a[k]=m(d[1]);else if(c===k){c=m(d[1]);break a}}c=a}return c}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/device-type.js",[],function(){function f(f){return h.test(f)}var h=/Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|Dolphin|Fennec|(hpw|web)OS|Zune|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Silk-Accelerated|Skyfire|NetFront/i,m=/WebView|\swv|(iPhone|iPod|iPad)(?!.*Safari)|Android.*(Version\/\d+\.\d+\s)|Linux; U; Android/i;return{isMobile:f,isDesktop:function(h){return!f(h)},isWebview:function(f){return m.test(f)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/dom.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js"],function(f){function h(a,b){return(b||document).querySelectorAll(a)}function m(a,b){return h(a,b)[0]}function l(a,g){function e(){clearTimeout(y);g(d);n.removeListener(d,"load",e)}g=g||function(){};if(b[a]||!a)return g(b[a]),b[a]||null;b[a]=document.createElement("link");var d=b[a];k.setAttribute(d,
"rel","stylesheet");k.setAttribute(d,"href",a);c.append(m("head"),d);n.addListener(d,"load",e);var y=setTimeout(function(){f.warn("Load timeout reached for stylesheet: ",{url:a});e()},5E3);return d}var d={each:function(a,b){var e;if(a.length===Number(a.length))for(e=0;e<a.length;e++){var c=b(a[e],e);if(!1===c)return!1}else for(e in a)if(Object.prototype.hasOwnProperty.call(a,e)&&(c=b(a[e],e),!1===c))return!1},extend:function(){var a,b,e=arguments[0]||{},c=1,d=arguments.length,k=!1,f=this.extend;"boolean"===
typeof e&&(k=e,e=arguments[1]||{},c=2);for("object"===typeof e||this.isFunction(e)||(e={});c<d;c++){var h=arguments[c];if(null!==h)for(a in h){var l=e[a];var q=h[a];e!==q&&(k&&q&&(this.isPlainObject(q)||(b=this.isArray(q)))?(b?(b=!1,l=l&&this.isArray(l)?l:[]):l=l&&this.isPlainObject(l)?l:{},e[a]=f(k,l,q)):void 0!==q&&(e[a]=q))}}return e},isFunction:function(a){return a&&"function"===typeof a&&a.call&&a.apply},isPlainObject:function(a){if("[object Object]"!==String(a)||a.nodeType||a.window&&a.window==
a)return!1;try{if(a.constructor&&!Object.prototype.hasOwnProperty.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(g){return!1}return!0},isArray:function(a){return a instanceof Array}};d.each.BREAK=!1;var n=function(){function a(a,b,e){for(var c=[],g=0;g<k.length;g++){var d=k[g];d.element==a&&d.eventType==b&&d.listener==e&&c.push({index:g,eventListener:d})}return c}function b(a){for(var b=[],e=0;e<k.length;e++){var c=k[e];c.element===a&&b.push(c)}return b}function e(a){this.originalEvent=
a;this.type=a.type;this.keyCode=a.keyCode;this.target=a.srcElement?a.srcElement:a.target}function c(b,e,c){c=a(b,e,c);0>=c.length?f.info("events.remove - Couldn't find exiting event listener for type \""+e+'" listener on element '+b):d.each(c,function(a){var c=a.index;a=a.eventListener;b.removeEventListener?b.removeEventListener(e,a.listenerWrapper,!1):b.detachEvent("on"+e,a.listenerWrapper);k.splice(c,1)})}var k=[];e.prototype={preventDefault:function(){var a=this.originalEvent;a.preventDefault?
a.preventDefault():a.returnValue=!1},stopPropagation:function(){var a=this.originalEvent;a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0}};return{addListener:function(b,c,g){function d(a){r&&(a=window.event);return g.call(b,new e(a))}if(0<a(b,c,g).length)f.warn("events.add - Listener already exists for event "+c+" on element "+b);else{var r=!b.addEventListener;k.push({element:b,eventType:c,listener:g,listenerWrapper:d});b.addEventListener?b.addEventListener(c,d,!1):b.attachEvent("on"+c,d)}},
triggerEvent:function(a,b,e){var c=document.createEvent("Event");e=d.extend({},e);var g=!1===!e.bubbles,k=!0===e.cancelable;delete e.bubbles;delete e.cancelable;c.initEvent(b,g,k);d.extend(c,e);a.dispatchEvent(c)},removeListener:c,clearListeners:function(a){a=b(a);d.each(a,function(a){c(a.element,a.eventType,a.listener)})}}}(),k=function(){function a(a){a=a.className;var b={};if(!a)return b;d.each(a.split(" "),function(a){b[a]=1});return b}function b(a){var b="";d.each(a,function(a,e){b+=" "+e});
return b.slice(1)}return{setAttribute:function(a,b,c){a.setAttribute(b,c);a[b]=c},getAttribute:function(a,b){return a.getAttribute(b)},removeAttribute:function(a,b){return a.removeAttribute(b)},addClass:function(e,c){var g=a(e);g[c]||(g[c]=1,e.className=b(g))},removeClass:function(e,c){var g=a(e);delete g[c];e.className=b(g)},getClassNames:function(a){return a.className.split(" ")}}}(),c=function(){function a(a){var b=document.createDocumentFragment(),e=document.createElement("div");e.innerHTML=a;
d.each(e.childNodes,function(a){1==a.nodeType&&b.appendChild(a)});return b}function b(a){var b;d.each(a.childNodes,function(a){if(!b&&1==a.nodeType)return b=a,d.each.BREAK});return b}return{prepend:function(e,c){var g=b(e),d=c;"string"===typeof c&&(d=a(c));g?e.insertBefore(d,g):e.appendChild(d)},append:function(b,c){var e=c;"string"===typeof c&&(e=a(c));b.appendChild(e)}}}(),b={};return{addEventListener:n.addListener,removeEventListener:n.removeListener,triggerEvent:n.triggerEvent,clearEventListeners:n.clearListeners,
getAttribute:k.getAttribute,setAttribute:k.setAttribute,removeAttribute:k.removeAttribute,addClass:k.addClass,removeClass:k.removeClass,getClassNames:k.getClassNames,prepend:c.prepend,append:c.append,query:h,queryFirst:m,isVisible:function(a,b){return!!(m(a,b)||{}).offsetParent},injectStylesheet:l,injectStylesheets:function(a,b){function e(a){--c||b(g)}b=b||function(){};if(0===a.length)b();else{var c=0,g=[];d.each(a,function(a){c++;setTimeout(function(){g.push(l(a,e))},1)})}},scrollIntoViewIfNeeded:function(a,
b){function c(a,b){return{start:a,length:b,end:a+b}}function g(a,c){return!1===b||c.start<a.end&&a.start<c.end?Math.min(a.start,Math.max(c.start,a.end-c.length)):(a.start+a.end-c.length)/2}function d(a,b){return{x:a,y:b,translate:function(c,e){return d(a+c,b+e)}}}function k(a,b){for(;a;)b=b.translate(a.offsetLeft,a.offsetTop),a=a.offsetParent;return b}var f=k(a,d(0,0)),h=d(a.offsetWidth,a.offsetHeight);a=a.parentNode;for(var l;a instanceof HTMLElement;)l=k(a,d(a.clientLeft,a.clientTop)),a.scrollLeft=
g(c(f.x-l.x,h.x),c(a.scrollLeft,a.clientWidth)),a.scrollTop=g(c(f.y-l.y,h.y),c(a.scrollTop,a.clientHeight)),f=f.translate(-a.scrollLeft,-a.scrollTop),a=a.parentNode}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/event-bus.js",[],function(){function f(){function f(d,c,b,a){if(!b)return!0;if("object"===typeof b){for(var g in b)d[c].apply(d,[g,b[g]].concat(a));return!1}if(n.test(b)){b=b.split(n);g=0;for(var e=b.length;g<e;g++)d[c].apply(d,[b[g]].concat(a));return!1}return!0}function d(d,c){var b,a=-1,g=d.length,e=c[0],f=c[1],k=c[2];switch(c.length){case 0:for(;++a<g;)(b=d[a]).callback.call(b.ctx);break;case 1:for(;++a<
g;)(b=d[a]).callback.call(b.ctx,e);break;case 2:for(;++a<g;)(b=d[a]).callback.call(b.ctx,e,f);break;case 3:for(;++a<g;)(b=d[a]).callback.call(b.ctx,e,f,k);break;default:for(;++a<g;)(b=d[a]).callback.apply(b.ctx,c)}}this._events={};var n=/\s+/;this.on=function(d,c,b){if(!f(this,"on",d,[c,b])||!c)return this;this._events||(this._events={});(this._events[d]||(this._events[d]=[])).push({callback:c,context:b,ctx:b||this});return this};this.off=function(d,c,b){var a,g,e;if(!this._events||!f(this,"off",
d,[c,b]))return this;if(!d&&!c&&!b)return this._events=void 0,this;var k=d?[d]:m.keys(this._events);var h=0;for(g=k.length;h<g;h++)if(d=k[h],a=this._events[d]){var l=[];this._events[d]=l;if(c||b){var n=0;for(e=a.length;n<e;n++){var p=a[n];(c&&c!==p.callback&&c!==p.callback._callback||b&&b!==p.context)&&l.push(p)}}l.length||delete this._events[d]}return this};this.once=function(d,c,b){function a(){var e=h.call(arguments);g.off(d,a,b);c.apply(this,e)}var g=this;this.on(d,a,b);return this};this.trigger=
function(k){if(!this._events)return this;var c=h.call(arguments,1);if(!f(this,"trigger",k,c))return this;var b=this._events[k],a=this._events.all;b&&d(b,c);a&&d(a,arguments);return this}}var h=Array.prototype.slice,m={isPlainObject:function(f){if("[object Object]"!==String(f)||f.nodeType||f.window&&f.window==f)return!1;try{if(f.constructor&&!Object.prototype.hasOwnProperty.call(f.constructor.prototype,"isPrototypeOf"))return!1}catch(d){return!1}return!0},keys:function(f){if(!this.isPlainObject(f))return[];
var d=[],h;for(h in f)Object.prototype.hasOwnProperty.call(f,h)&&d.push(h);return d},_idCounter:0,uniqueId:function(f){var d=String(++this._idCounter);return f?f+d:d}};return{create:function(){return new f}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js",[],function(){function f(a,b,c){d||(d=b.getGlobalServices().getJsLoggingService());d[a](c)}function h(e,d,f){var h=String(extole.CORE_ROOT).match(/coreAssetsVersion=(\d+)/);f=f||{};f.pageId=k;f.referer=c;f.coreAssetsVersion=h&&h[1];try{var r=[d||"no message","START_JSON",JSON.stringify(f),"END_JSON"].join(" ")}catch(p){l("Failed to stringify log's json data",{exception:p});return}if(!extole.LOG_EXCLUDE_REGEX||
!r.match(extole.LOG_EXCLUDE_REGEX)){g[r]=++g[r]||1;if(b[e]>=b[extole.LOG_LEVEL_CONSOLE]&&(d=e+" "+r,window.console))if(window.console[e.toLowerCase()])window.console[e.toLowerCase()](d);else window.console.log(d);b[e]>=b[extole.LOG_LEVEL_REMOTE]&&(d=g[r],a[d]&&m(e,r+(1<d?" log count: "+d:"")))}}function m(a,b){extole.require(["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/api.js"],function(c){c.post("/api/v4/debug/logs",{level:a,message:b},null,{headers:{"Content-Type":"application/x-www-form-urlencoded"}})})}
function l(a,b){h("ERROR",a,b)}var d;if("undefined"===typeof window)return{debug:function(a,b){f("debug",a,b)},info:function(a,b){f("info",a,b)},warn:function(a,b){f("warn",a,b)},error:function(a,b){f("error",a,b)},LOGGING_ENDPOINT:"/api/v4/debug/logs"};var n=extole.IS_DEBUG_ENABLED?"DEBUG":"OFF",k=String((new Date).getTime()),c=window.location.href,b={DEBUG:0,INFO:1,WARN:2,ERROR:3,OFF:4},a={1:!0,3:!0,10:!0,30:!0,100:!0,250:!0,500:!0,1E3:!0};extole.LOG_EXCLUDE_REGEX=extole.LOG_EXCLUDE_REGEX||void 0;
extole.LOG_LEVEL_CONSOLE=extole.LOG_LEVEL_CONSOLE||n;extole.LOG_LEVEL_REMOTE=extole.LOG_LEVEL_REMOTE||"WARN";var g={};return{debug:function(a,b){h("DEBUG",a,b)},info:function(a,b){h("INFO",a,b)},warn:function(a,b){h("WARN",a,b)},error:l,LOGGING_ENDPOINT:"/api/v4/debug/logs"}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/Timer.js",[],function(){return function(){var f=this,h;this.start=function(){if(h)throw Error("Timer.start has already been called");h=new Date;return f};this.getElapsedTime=function(){if(!h)throw Error("Timer has not been started");return new Date-h}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/type.js",[],function(){function f(f,d){return function(l){return h(f,l,d)}}function h(f,d,h){h=h||{};f=Object.prototype.toString.call(d)==="[object "+f+"]";d=d&&h.construct?d.constructor===h.construct:!0;return(h.negate?!f:f)&&d}var m=/\[object (Function|Array|String|Boolean|Number|Undefined|Null)\]/;return{isPlainJs:function(f){return this.isPlainObject(f)||m.test(Object.prototype.toString.call(f))},
isJavaMap:function(f){return"undefined"!==typeof Java&&Java.type?f instanceof Java.type("java.util.Map"):!1},isPlainObject:f("Object",{construct:Object}),isPlainFunction:f("Function"),isArray:f("Array"),isString:f("String"),isBoolean:f("Boolean"),isNumber:f("Number"),isUndefined:f("Undefined"),isDefined:f("Undefined",{negate:!0}),isNull:f("Null"),test:h}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/uri.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/collection.js"],function(f){function h(c){var b={};(function r(c,e){for(var d in c){var g=c[d],f=(e?e+".":"")+d;"[object Object]"===Object.prototype.toString.call(g)?r(g,f):l(f)&&(b[f]=g)}})(c);return b}function m(c){try{return decodeURIComponent(c)}catch(b){return c}}function l(c){return"__proto__"!==c&&"prototype"!==
c&&"constructor"!==c}function d(c,b,a){b=(b||[]).concat("object"===typeof extole&&extole.PROGRAM?extole.PROGRAM.siteRegexPatterns:[]);a=n(a||location.href);c=n(c);return(/^https?:\/\//.test(c)?f.find(b,function(a){var b=k.exec(c);return(new RegExp(a)).test(b&&b[1])}):1)?c:a}function n(c){return c.replace(/(j|%4A|%6A)(a|%41|%61)(v|%56|%76)(a|%41|%61)(s|%53|%73)(c|%43|%63)(r|%52|%72)(i|%49|%69)(p|%50|%70)(t|%54|%74)(:|%3A)/gi,"")}var k=/^https?:\/\/([^/:?#]+)/i;return{serialize:function(c){var b="",
a;for(a in c)b+="&"+encodeURIComponent(a)+"="+encodeURIComponent(String(c[a]));return b.replace(/^&/,"?")},deserialize:function(c){var b={};if(!c)return b;c=(c.match(/^\?/)?c.slice(1):c).split("&");for(var a=0;a<c.length;a++){var d=c[a].split("="),e=m(d[0]);d=m(d[1]);l(e)&&(b[e]=d)}return b},objectToDotNotation:h,dotNotationToObject:function(c){var b={};c=h(c);for(var a in c){for(var d=b,e=a.split("."),f=e.pop();e.length;){var k=e.shift();l(k)&&(d[k]=d[k]||{},d=d[k])}l(f)&&(d[f]=c[a])}return b},decodeComponent:m,
encodeComponent:function(c){return encodeURIComponent(c)},getSafeRedirectUrl:d,executeSafeRedirect:function(c,b,a){window.location.href=d(c,b,a)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/ajax.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/collection.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/uri.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/type.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js"],function(f,h,
m,l){function d(b,a){function c(){4!==b.readyState||A||(A=!0,String(b.status||200).match(/^[23]/)?"function"===typeof z?z.call(b,b.responseText,b):l.warn("'complete' callback must be a function."):C.call(b,b.statusText,b.status),n())}function d(a){A||(A=!0,l.error("Error with url "+x+"= "+w.join(","),k(a)),C.call(b,b.statusText,b.status))}function k(c){return{eventType:c&&c.type||null,options:a,readyState:b.readyState,response:b.response,responseText:b.responseText,responseType:b.responseType,responseURL:b.responseURL,
responseXML:b.responseXML,status:b.status,statusText:b.statusText,timeout:b.timeout,responseHeaders:b.getAllResponseHeaders()}}function n(a){0>x.indexOf(l.LOGGING_ENDPOINT)&&l.debug("ajax request complete",k(a))}var w=Array.prototype.slice.call(arguments),u=a.headers||{},p=a.xhrFields||{},x=a.url||"",q=a.data||"",t=(a.type||"get").toUpperCase(),z=a.complete||function(){},C=a.error||function(){};m.isPlainObject(q)&&("GET"===t?(x+=h.serialize(q),q=null):q=JSON.stringify(q));b.open(t,x,!0);f.merge(b,
p);f.each(u,function(a,c){try{b.setRequestHeader(c,a)}catch(E){l.error("AJAX ERROR: Couldn't set request header "+c+" to "+a)}});var A=!1;b.onload=c;b.onreadystatechange=c;b.onerror=d;b.ontimeout=d;b.onabort=n;b.send(q)}function n(b){f.each(b,function(a,c){"content-type"===c.toLowerCase()&&delete b[c]})}function k(b){b=b||{};var a=!1;for(var f=0;f<c.length;f++){try{a=c[f]()}catch(e){continue}break}d(a,b);return a}var c=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},
function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];k.convertToFormUrlEncoded=function(b,a){function c(a){var b={};f.each(a,function(a,d){d=0<=d.indexOf(".")?'"'+d+'"':d;m.isPlainObject(a)&&(a=c(a));b[d]=a});return b}var d=[];n(b);b["content-type"]="application/x-www-form-urlencoded";a=c(a);a=f.flatten(a);f.each(b,function(a,c){"content-type"!==c.toLowerCase()&&(d.push("::headers."+c+"="+a),delete b[c])});f.each(a,function(a,b){m.isUndefined(a)||
d.push(encodeURIComponent(b)+"="+encodeURIComponent(a))});return d.join("&")};k.convertToMultipartFormData=function(b,a){var c=new FormData;f.each(a,function(a,b){c.append(b,a)});n(b);return c};return k});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/program.js",[],function(){return{getName:function(){return extole.PROGRAM.name},getProgramDomain:function(){return extole.PROGRAM.programDomain},getSitePatterns:function(){return extole.PROGRAM.sitePatterns},getSiteRegexPatterns:function(){return extole.PROGRAM.siteRegexPatterns},getProtocol:function(){return"https://"}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/token-store.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/ExtoleError.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/collection.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/event-bus.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/cookie.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/ajax.js".split(" "),
function(f,h,m,l,d,n){function k(){function e(){v[a.MEMORY]=v[a.MEMORY]||new x;v[a.COOKIE]=v[a.COOKIE]||new q;v[a.LOCAL_STORAGE]=v[a.LOCAL_STORAGE]||new t;extole.COOKIES_DISABLED&&(v[a.COOKIE].remove(),delete v[a.COOKIE]);extole.LOCAL_STORAGE_ALWAYS_ENABLED||extole.LOCAL_STORAGE_ENABLED_WHEN_CONSENTED||extole.LOCAL_STORAGE_ENABLED_WHEN_UNCONSENTED||(v[a.LOCAL_STORAGE].remove(),delete v[a.LOCAL_STORAGE])}function k(a){function b(d,e){c+=1;d?5>c?y(b):(d="Failed to fetch access token after 5 attempts. Last Error: "+
d.message,m.error(d),a(Error(d))):a(null,e)}var c=0;y(b)}function y(a){w("POST","/api/v5/token",null,function(b,c){a(b,c)})}function w(a,b,c,d){function e(a,b){try{var c=JSON.parse(a)}catch(H){b(H);return}b(null,c)}c=c||u();var g="https://"+extole.PROGRAM.programDomain+b+(c?"?access_token="+c:"");n({url:g,type:a,headers:{"content-type":"application/json"},complete:function(a){e(a,d)},error:function(c,k){var l=this,q="Api request to "+b+" failed: "+k+" "+c,m={method:a,url:g,statusText:c||null,http_status_code:k||
null};e(l.responseText,function(a,b){if(a){a="Failed to parse api error response as json";var c="json_parse_error";b=h.merge({response:l.responseText},m)}else a=b.message||q,c=b.code||"failed_api_request",b=h.merge({},b,m);d(new f(a,c,b))})}})}function u(){var a=B===b.YEAR?A():D();return(a=h.find(a,function(a){a=a.get();return!("string"!==typeof a||"undefined"===a||"null"===a||!a.length)}))?a.get():null}function p(a,c){var d=u();if(!a&&d)a=d;else if(!a&&!d)return;var e=d!==a;B=Object.prototype.hasOwnProperty.call(b,
c)&&c||(e||!B?z():B);C(B);h.each(B===b.YEAR?A():D(),function(b){b.set(a,B)});e&&E.trigger("change:access_token");d&&e&&m.debug("ACCESS_TOKEN_CHANGE - the access token changed from: "+d+", to: "+a)}function x(){var a={};this.get=function(){return a.extole_access_token};this.set=function(b){a.extole_access_token=b};this.remove=function(){delete a.extole_access_token}}function q(){this.get=function(){return d("extole_access_token")};this.set=function(a,b){d("extole_access_token",a,{expires:g[b.toUpperCase()],
path:"/",samesite:"strict"})};this.remove=function(){d("extole_access_token","",{expires:-1,path:"/"})}}function t(){var a;(function(){var b="test"+(new Date).getTime();try{localStorage.setItem(b,b),localStorage.removeItem(b)}catch(G){a=!1;return}a=!0})();this.get=function(){return a?localStorage.getItem("extole_access_token"):null};this.set=function(b){a&&localStorage.setItem("extole_access_token",b)};this.remove=function(){a&&localStorage.removeItem("extole_access_token")}}function z(){if(extole.CORE_CONFIG.isCookieConsentEnabled)switch(extole.CORE_CONFIG.cookieConsentPolicy){case c.COOKIE_CONSENT_OR_SESSION_COOKIE:return b.SESSION;
case c.COOKIE_CONSENT_OR_NO_COOKIE:return b.NO_COOKIE;default:return b.NO_COOKIE}return b.YEAR}function C(){var a=B===b.YEAR?A():D();h.each(v,function(b){0>a.indexOf(b)&&b.remove()})}function A(){var b=[a.MEMORY];Object.prototype.hasOwnProperty.call(v,a.COOKIE)&&b.push(a.COOKIE);(extole.LOCAL_STORAGE_ENABLED_WHEN_CONSENTED||extole.LOCAL_STORAGE_ALWAYS_ENABLED)&&b.push(a.LOCAL_STORAGE);return b.map(function(a){return v[a]})}function D(){var b=[a.MEMORY];extole.CORE_CONFIG.cookieConsentPolicy===c.COOKIE_CONSENT_OR_SESSION_COOKIE&&
Object.prototype.hasOwnProperty.call(v,a.COOKIE)&&b.push(a.COOKIE);(extole.LOCAL_STORAGE_ENABLED_WHEN_UNCONSENTED||extole.LOCAL_STORAGE_ALWAYS_ENABLED)&&b.push(a.LOCAL_STORAGE);return b.map(function(a){return v[a]})}var B,E=l.create(),v={};e();this.fetch=function(a){a=a||function(){};k(function(b,c){var d=c.access_token;d&&p(d);a(b,c,B)})};this.getTokenDetails=function(a){a=a||function(){};w("GET","/api/v5/token",u(),a)};this.get=u;this.set=p;this.remove=function(){B=z();h.each(v,function(a){a.remove()})};
this.setUnconsented=function(){B=z();p()};this.initializeStores=e;this.events=E}var c={COOKIE_CONSENT_DISABLED:"COOKIE_CONSENT_DISABLED",COOKIE_CONSENT_OR_SESSION_COOKIE:"COOKIE_CONSENT_OR_SESSION_COOKIE",COOKIE_CONSENT_OR_NO_COOKIE:"COOKIE_CONSENT_OR_NO_COOKIE"},b={NO_COOKIE:"NO_COOKIE",SESSION:"SESSION",YEAR:"YEAR"},a={MEMORY:"MEMORY",COOKIE:"COOKIE",LOCAL_STORAGE:"LOCAL_STORAGE"},g={YEAR:365,SESSION:null};extole.tokenStore=extole.tokenStore?extole.tokenStore:new k;return extole.tokenStore});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/metric-registry.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/program.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/ajax.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/token-store.js"],function(f,h,m){function l(d,c,b){b={metric_type:d,key:c,value:b};d={"Content-Type":"application/x-www-form-urlencoded",
"X-Extole-App":"javascript_sdk"};m.get()&&(d.Authorization="Bearer+"+m.get(),c=[f.getProtocol(),f.getProgramDomain(),"/api/v4/debug/metrics"].join(""),b=h.convertToFormUrlEncoded(d,b),h({url:c,type:"POST",headers:d,data:b,xhrFields:{withCredentials:!0}}))}function d(d){this.increment=function(c){l("COUNTER",d,c)}}function n(d){this.update=function(c){l("HISTOGRAM",d,c)}}return{histogram:function(d){return new n(d)},counter:function(f){return new d(f)}}});
extole.define("CreativeRenderContext",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/uri.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/collection.js"],function(f,h){function m(d,f,c){this.getElement=function(){return c};this.getName=function(){return d};this.getData=function(){return f};this.getParameters=function(){return f}}function l(){this.getName=function(){return extole.PROGRAM.name};this.getProgramDomain=function(){return extole.PROGRAM.programDomain};
this.getSitePatterns=function(){return extole.PROGRAM.sitePatterns};this.getSiteRegexPatterns=function(){return extole.PROGRAM.siteRegexPatterns}}function d(){this.backendTargetingEnabled=function(){return!0};this.cookieConsentEnabled=function(){return extole.CORE_CONFIG.isCookieConsentEnabled}}return function(n,k,c,b){var a=new m(n,k,c),g=new l,e=new d;this.getZone=function(){return a};this.getProgram=function(){return g};this.getCreativeData=function(){var b=f.dotNotationToObject(f.deserialize(location.search)),
c=f.dotNotationToObject(a.getParameters());return h.merge(b.extole_creative,c.creative)};this.getCoreConfig=function(){return e};this.getLocale=function(){return b||null}}});
extole.define("find-element-by-id",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/metric-registry.js"],function(f,h){function m(f,d,h){function k(){if(d())h();else{f();var b=setTimeout;c||(c=10);var a=500<c?500:c*=1.1;b(k,a)}}var c;k()}return function(l,d){var n=(new Date).getTime(),k=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_NOT_FOUND||3E3,c=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_FOUND||
2E3,b=!1,a;m(function(){a=document.getElementById(l)},function(){var d=(new Date).getTime()-n,e=!!a;e&&d>=c?(h.histogram("zone_element_found_slow").update(d),f.warn("EXTOLE_ELEMENT_FOUND_SLOW: Scan duration: "+d+"ms, element id: "+l)):!extole.isFindElementBeforeZoneRequest&&!b&&d>=k&&(b=!0,h.histogram("zone_element_not_yet_found").update(d),f.warn("EXTOLE_ELEMENT_NOT_YET_FOUND: Scan duration: "+d+"ms, element id: "+l));return e},function(){d(a)})}});
extole.define("ensure-element",["find-element-by-id"],function(f){return function(h,m){h.element?m(h.element):h.element_id?f(h.element_id,m):m(document.body.appendChild(document.createElement("div")))}});
extole.define("pending-zone-service","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/device-type.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/dom.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/type.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/collection.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/metric-registry.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/token-store.js CreativeRenderContext ensure-element".split(" "),function(f,
h,m,l,d,n,k,c,b){function a(a,d){d=d||function(){};var f=a.name,l=e(a.data),m=Date.now();x(f);this.resolve=function(e,q,p,t){k.set(q,p);r(a)&&(q=g(f,"time_to_zone_response_ms"),p=Date.now()-m,n.histogram(q).update(p));b(a,function(b){a.element=b;r(a)&&y(a.element,function(){var a=g(f,"time_to_first_html_ms"),b=Date.now()-m;n.histogram(a).update(b)});h.clearEventListeners(a.element);b=new c(f,l,a.element,t);e(b);d(null,b.getZone())})}}function g(a,b){var c=document.getElementsByTagName("*").length;
c=2500<c?"xx_large":1500<c?"x_large":1E3<c?"large":500<c?"medium":"small";var d=f.isMobile((window.navigator||{}).userAgent)?"mobile":"desktop";return[a,d,c,b].join("_")}function e(a){a=d.merge({},a);delete a.campaign_id;delete a.extole_campaign_id;return a}function r(a){return u.test(a.name)||u.test((a.data||{}).redirect)?!0:!1}function y(a,b){var c=document.createElement("div");c.style.display="none";a.appendChild(c);w(c,b)}function w(a,b){if(window.MutationObserver){var c=new MutationObserver(function(e){d.each(e,
function(e){e.removedNodes&&d.each(e.removedNodes,function(d){d===a&&(b(),c.disconnect())})})});a.parentNode&&c.observe(a.parentNode,{childList:!0})}}var u=/_experience$/,p={},x=function(){var a={};return function(b){m.isUndefined(a[b])&&(a[b]=0);a[b]++;if(5===a[b]){b="duplicate_zone_requests : "+b;var c=d.filter(extole.q.history,function(a){return a.name&&"createZone"===a.name});c=d.map(c,function(a){delete (a.args[0]||{}).element;return a});l.warn(b,c)}}}();return{get:function(a){if(!p[a])throw Error("Pending zone does not exist for id: "+
a);return p[a]},create:function(){var b=Math.floor(1E9*Math.random()),c=0;return function(d,e){c++;var f=b+"."+c;p[f]=new a(d,e);return f}}()}});
extole.define("create-zone","extole-uri-parser https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/uri.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/collection.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/dom.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/program.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/token-store.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/ajax.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/ExtoleError.js pending-zone-service".split(" "),function(f,
h,m,l,d,n,k,c,b){function a(a){var b=document.createElement("script");l.setAttribute(b,"src",a);l.setAttribute(b,"async","");l.append(l.queryFirst("head")||l.queryFirst("body"),b);return b}return function(g,e,r){function y(){z&&(t.jwt=z);C&&(t.access_token=C);D&&(t.debug="true");t.extole_app="javascript_sdk";x=[A,"/zones/",g.name].join("");var b=a(x+h.serialize(t));b.onload=p;b.onerror=function(){u(new c("Zone script tag request failed","zone_tag_request_failure",null))}}function w(){var a={"Content-Type":"application/x-www-form-urlencoded",
Accept:"text/javascript","X-Extole-App":"javascript_sdk"};x=A+"/zones/"+g.name;z&&(a["X-Extole-Jwt"]=z,delete t.jwt);C&&(a.Authorization="Bearer+"+C);D&&(a["X-Extole-Debug"]="true");var b=k.convertToFormUrlEncoded(a,t);k({url:x,type:"POST",headers:a,data:b,complete:function(a,b){var d=/^text\/html(;|$)/,e=/^text\/plain(;|$)/;b=b.getResponseHeader("Content-Type");if(/^text\/javascript(;|$)/.test(b))var f=a;else d.test(b)?(d=document.createElement("div"),d.innerHTML=a,f=l.queryFirst("script",d).innerHTML):
e.test(b)&&!a?u(new c("Empty response","empty_response",null,"info")):u(new c("Received invalid content type: '"+b+"'","invalid_content_type",null,"warn"));if(f)try{(new Function(f))()}catch(F){u(new c("Error in zone script - MESSAGE: "+F.message+" STACK: "+F.stack,"zone_script_error"))}p()},error:function(a,b){try{var d=JSON.parse(this.responseText)}catch(G){d={status:b||null,statusText:a||null}}u(new c(d.message||"Ajax zone request failed",d.code||null,d))},xhrFields:{withCredentials:!0}})}function u(a){var b=
"Problem creating zone with "+(extole.CORE_CONFIG.isZonePostEnabled?"POST":"GET"),d=m.merge({originalMessage:a.message,zoneRequestUrl:x||null,zoneDefinition:g},a.data);e(new c(b,a.code||"zone_request_failed",d,a.logLevel||"error"));p()}function p(){"function"===typeof r&&setTimeout(r,500)}e=e||function(){};var x,q=h.deserialize(location.search),t=m.merge({},g.data||g.parameters),z=g.jwt||t.jwt||q.extole_jwt,C=n.get(),A=[d.getProtocol(),d.getProgramDomain()].join(""),D=t.debug&&"false"!==t.debug||
extole.IS_DEBUG_ENABLED;extole.isPassRefererInZoneData&&(t.referer=location.href);extole.CORE_CONFIG.isGlobalZoneParametersEnabled&&(q=f.parseGlobalZoneParameters(q),t=m.merge(t,q));if(extole.createZonePrehandler&&(q=extole.createZonePrehandler(g,t),!1===q)){u(new c("Zone request cancelled","zone_request_cancelled",null,"info"));return}g.element_id&&(t.element_id=g.element_id);g.data=t;t.zone_id=b.create(g,e);t=m.flatten(t);extole.CORE_CONFIG.isZonePostEnabled?w():y()}});
extole.define("create-zone-executor",["create-zone","ensure-element","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/logger.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=144/common/client/token-store.js"],function(f,h,m,l){function d(d,h,n){function p(a){if(a)r(a);else{g=!0;var b=Array.prototype.slice.call(arguments);(h||function(){}).apply(null,b);q()}}function r(b){function f(){setTimeout(function(){k(d,h,n)},1)}n+=1;if(5>n)if(c(b))g=
!1,l.remove(),f();else if("zone_tag_request_failure"!==b.code||extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled)if("invalid_content_type"===b.code)f();else m[b.logLevel||"error"](b.toString());else a.stop(),e(function(b,c){c?g=!0:!1===c&&(g=!1,l.remove());a.start();f()});else m[b.logLevel||"error"](b.toString()),m.warn("ERROR_WOULD_BE_PASSED_TO_CREATE_ZONE_CALLBACK")}var q;a.push(function(a){q=b(a);f(d,p,q);g&&q()})}function n(a){function b(){for(;c.length;)c.shift().apply(null,arguments)}
var c=[],d=!1;return function(e){c.push(e);d||(d=!0,a(function(){d=!1;b.apply(null,arguments)}))}}function k(a,b,c){function e(){var e=!!l.get(),f=!!a.element;!extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled&&!e||extole.isFindElementBeforeZoneRequest&&!f||d(a,b,c)}c=Number(c)||0;l.get()||extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled||r(e);extole.isFindElementBeforeZoneRequest&&h(a,function(b){a.element=b;e()});e()}function c(a){a=a||{};return a.data&&403===a.data.http_status_code&&
("invalid_access_token"===a.code||"expired_access_token"===a.code)}function b(a){var b=!1;return function(){var c=Array.prototype.slice.call(arguments);b||(b=!0,a.apply(null,c))}}var a=new function(){var a=0,b=[],c=this,d=!1;this.push=function(a){b.push(a);this.next()};this.next=function(){function e(){a--;c.next()}if(!d)for(;1>a&&b.length;)b.shift()(e),a++};this.start=function(){d=!1;this.next()};this.stop=function(){d=!0}},g=!1,e=n(function(a){l.getTokenDetails(function(b,d){b?c(b)?a(null,!1):a(b):
a(null,0<d.expires_in)})}),r=n(l.fetch);return{initiateExecution:k}});